version: "3"

services:
  # server
  server:
    build: ./
    environment:
      - MONGO_USER=user
      - MONGO_PASSWORD=password
      - MONGO_URL=localhost
      - MONGO_PORT=27017
      - MONGO_DATABASE=social-media
      - JWT_SECRET=secret
      - JWT_EXPIRES_IN=1d
    ports:
      - "7001:7001"
    command: npm start
    volumes:
      - .:/app
  test:
    build: .
    command: npm test
    volumes:
      - .:/app
