version: "3"

services:
  # server
  server:
    build: ./
    environment:
      - ENV=dev
      - MONGO_USER=root
      - MONGO_PASSWORD=example
      - MONGO_URL=db
      - MONGO_PORT=27017
      - MONGO_DATABASE=social-media
      - JWT_SECRET=secret
      - JWT_EXPIRES_IN=1d
    ports:
      - "7001:7001"
    depends_on:
      - db

  # database
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  # database admin
  ui:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@db:27017/
    depends_on:
      - db