version: "3"

services:
  # server
  server:
    build: ./
    environment:
      - MONGO_USER=qwert-12345
      - MONGO_PASSWORD=DgziTFvjoCqnjjvT
      - MONGO_URL=reunion.d3uprge.mongodb.net
      - MONGO_PORT=27017
      - MONGO_DATABASE=social-media
      - JWT_SECRET=secret
      - JWT_EXPIRES_IN=1d
    ports:
      - "7001:7001"  
    command: npm start
    volumes:
      - .:/app
  test:
    build: .
    command: npm test
    volumes:
      - .:/app
